apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-betaling-backend
  namespace: ofk-no
spec:
  port: 8080
  orgId: ofk.no
  image: ghcr.io/fintlabs/fint-betaling-backend:latest
  imagePullPolicy: Always
  env:
    - name: fint.betaling.org-id
      value: ofk.no
    - name: fint.betaling.default-org-id
      value: ofk.no
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx4250M'
    - name: fint.betaling.invoice-update-rate
      value: '3600000'
    - name: fint.betaling.principal-matching-strategy
      value: 'byOrgnummer'
    - name: fint.client.enabled
      value: 'true'
    - name: fint.client.base-url
      value: 'https://api.felleskomponent.no'
    - name: fint.betaling.client-name
      value: 'FINT-Betaling'
    - name: fint.betaling.default-org-id
      value: 'ofk.no'
    - name: fint.betaling.default-school-org-id
      value: ofk.no
    - name: fint.betaling.date-range
      value: '7, 14, 30'
    - name: fint.betaling.invoice-update-cron
      value: '0 0 0 31 2 ?'
    - name: fint.betaling.endpoints.environment
      value: 'api'
    - name: logging.level.root
      value: 'INFO'
  database:
    database: fint-core
  url:
    hostname: betaling.felleskomponent.no
    basePath: /api/ofk-no
  ingress:
    enabled: true
  resources:
    limits:
      memory: "5Gi"
      cpu: "2"
    requests:
      memory: "512Mi"
      cpu: "250m"
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }