apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml
  - fint_client.yaml
namespace: ofk-no
labels:
  - pairs:
      app.kubernetes.io/name: fint-betaling-backend
      app.kubernetes.io/instance: fint-betaling-backend_ofk-no
      app.kubernetes.io/version: "latest"
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: fint-betaling
      fintlabs.no/org-id: ofk.no
      fintlabs.no/team: core