apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress-route.yaml
  - service.yaml
  - database.yaml
namespace: fintlabs-no
commonLabels:
  app.kubernetes.io/name: fint-betaling-backend
  app.kubernetes.io/instance: fint-betaling-backend_fintlabs-no
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-betaling
  fintlabs.no/team: core