apiVersion: v1
kind: Service
metadata:
  name: betaling
  annotations: {service.beta.kubernetes.io/azure-load-balancer-internal: 'true'}
spec:
  selector:
    app: betaling
  type: LoadBalancer
  ports:
    - {name: '8080', port: 8080}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: betaling
spec:
  selector:
    matchLabels:
      app: betaling
  template:
    metadata:
      labels:
        app: betaling
    spec:
      containers:
        - name: betaling
          image: fintlabs.azurecr.io/betaling:PR-10.3
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "1Gi"
              cpu: "250m"
          ports:
            - containerPort: 8080
          env:
            - {name: TZ, value: Europe/Oslo}
            - {name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx1G -verbose:gc'}
            - name: fint.oauth.enabled
              value: "true"
            - name: fint.oauth.access-token-uri
              value: https://idp.felleskomponent.no/nidp/oauth/nam/token
            - name: fint.oauth.scope
              value: fint-client
            - name: fint.oauth.client-id
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: fake-adapter
            - name: fint.oauth.client-secret
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: fake-adapter
            - name: fint.oauth.username
              valueFrom:
                secretKeyRef:
                  key: username
                  name: fake-adapter
            - name: fint.oauth.password
              valueFrom:
                secretKeyRef:
                  key: password
                  name: fake-adapter
            - name: spring.data.mongodb.uri
              valueFrom:
                secretKeyRef:
                  name: fint-mongo
                  key: mongodb
            - name: spring.data.mongodb.database
              value: betaling-beta
