spring:
  mvc:
    dispatch-options-request: true
  data:
    mongodb:
      uri: "mongodb://localhost:27017/fintBetaling"


springfox:
  title: 'FINT-Betaling'
  version: '0.0.1-SNAPSHOT'

fint:
  betaling:
    endpoints:
      invoice: "https://beta1.felleskomponent.no/administrasjon/okonomi/fakturagrunnlag"
      orderLine: "https://beta1.felleskomponent.no/administrasjon/okonomi/varelinje"
      mvaCode: "https://beta1.felleskomponent.no/administrasjon/okonomi/mvakode"
      employer: "https://beta1.felleskomponent.no/administrasjon/okonomi/oppdragsgiver"
      student: "https://play-with-fint.felleskomponent.no/utdanning/elev/elev"
      basisgruppe: "https://play-with-fint.felleskomponent.no/utdanning/elev/basisgruppe"
      undervisningsgruppe: "https://play-with-fint.felleskomponent.no/utdanning/timeplan/undervisningsgruppe"
      kontaktlarergruppe: "https://play-with-fint.felleskomponent.no/utdanning/elev/kontaktlarergruppe"
