spring:
  profiles:
    include:
      - db
  cache:
    caffeine:
      spec: expireAfterWrite=2h
    cache-names: me, organisations, persons
    type: CAFFEINE
  mvc:
    dispatch-options-request: true
  webflux:
    base-path: /api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token?resourceServer=fint-api
        registration:
          fint:
            authorization-grant-type: password
            provider: fint-idp
            scope: fint-client
            client-id: ${fint.core.oauth2.client-id}
            client-secret: ${fint.core.oauth2.client-secret}

management:
  health:
    readinessState:
      enabled: true
  endpoints:
    health:
      probes:
        enabled: true
    web:
      exposure:
        include: info, health, metrics, prometheus

fint:
  client:
    registration-id: fint
    username: ${fint.core.oauth2.username}
    password:  ${fint.core.oauth2.password}

  oauth:
    enabled: true
    scope: fint-client
    request-url: https://idp.felleskomponent.no/nidp/oauth/nam/userinfo

  betaling:
    authorized-role: https://role-catalog.vigoiks.no/vigo/elevfakturering/user
    authorized-role-admin: https://role-catalog.vigoiks.no/vigo/elevfakturering/admin
    date-range: "7, 14, 30"
    invoice-update-rate: "300000"
    invoice-update-cron: '0 30 16 ? * MON-FRI'
    demo-user-employee-id: "100006"
    demo: "false"
    principal-matching-strategy: "byOrgnummer"

