spring:
  profiles: pwf
  mvc:
    dispatch-options-request: true
  data:
    mongodb:
      uri: "mongodb://localhost:27017/fintBetaling"

security:
  basic:
    enabled: false

springfox:
  title: 'FINT-Betaling'
  version: '0.0.1-SNAPSHOT'

fint:
  oauth:
    enabled: true
    username: pwfatut
    password: pwfatut
    client-id: 6e1cf7b4-b107-42b3-9435-8fda70726c6a
    client-secret: 6y4FUuP9BfAXeVqguNKT0ofToIwN5RdB1PaUvx_nCMiQbH9NeGq3pp0jQB9zOQ0APOxEbodzJXp-8RVux6318A
    access-token-uri: https://namidp01.rogfk.no/nidp/oauth/nam/token
    request-url: https://beta.felleskomponent.no/utdanning/elev/person

  betaling:
    client-name: "FINT-Betaling"
    default-org-id: "fake.no"
    default-school-org-id: "970123459"
    date-range: "7, 14, 30"
    demo: "true"
    demo-user-feide: "nora.lys@osloskole.no"
    principal-matching-strategy: "byOrgnummer"
    endpoints:
      environment: "play-with-fint"
      #invoice: "https://play-with-fint.felleskomponent.no/betaling/fakturagrunnlag"
      #order-line: "https://play-with-fint.felleskomponent.no/betaling/varelinje"
      #mva-code: "https://play-with-fint.felleskomponent.no/betaling/mvakode"
      #employer: "https://play-with-fint.felleskomponent.no/betaling/oppdragsgiver"
      school: "https://play-with-fint.felleskomponent.no/utdanning/utdanningsprogram/skole"
      basisgruppe: "https://play-with-fint.felleskomponent.no/utdanning/elev/basisgruppe"
      teaching-group: "https://play-with-fint.felleskomponent.no/utdanning/timeplan/undervisningsgruppe"
      kontaktlarergruppe: "https://play-with-fint.felleskomponent.no/utdanning/elev/kontaktlarergruppe"
      person: "https://play-with-fint.felleskomponent.no/utdanning/elev/person"
      student-relation: "https://play-with-fint.felleskomponent.no/utdanning/elev/elevforhold"

