spring:
  mvc:
    dispatch-options-request: true
  data:
    mongodb:
      uri: "mongodb://localhost:27017/fintBetaling"

springfox:
  title: 'FINT-Betaling'
  version: '0.0.1-SNAPSHOT'

fint:
  oauth:
    enabled: true
    username: pwfatut
    password: pwfatut
    client-id: 6e1cf7b4-b107-42b3-9435-8fda70726c6a
    client-secret: 6y4FUuP9BfAXeVqguNKT0ofToIwN5RdB1PaUvx_nCMiQbH9NeGq3pp0jQB9zOQ0APOxEbodzJXp-8RVux6318A
    access-token-uri: https://namidp01.rogfk.no/nidp/oauth/nam/token
  betaling:
    client-name: "FINT-Betaling"
    endpoints:
      invoice: "https://beta1.felleskomponent.no/administrasjon/okonomi/fakturagrunnlag"
      order-line: "https://beta1.felleskomponent.no/administrasjon/okonomi/varelinje"
      mva-code: "https://beta1.felleskomponent.no/administrasjon/okonomi/mvakode"
      employer: "https://beta1.felleskomponent.no/administrasjon/okonomi/oppdragsgiver"
      student: "https://play-with-fint.felleskomponent.no/utdanning/elev/elev"
      basisgruppe: "https://play-with-fint.felleskomponent.no/utdanning/elev/basisgruppe"
      undervisningsgruppe: "https://play-with-fint.felleskomponent.no/utdanning/elev/undervisningsgruppe"
      kontaktlarergruppe: "https://play-with-fint.felleskomponent.no/utdanning/elev/kontaktlarergruppe"
    date-range: "7, 14, 30"

security:
  basic:
    enabled: false