spring:
  profiles: pwf
  mvc:
    dispatch-options-request: true
  data:
    mongodb:
      uri: "mongodb://localhost:27017/fintBetaling"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
        registration:
          fint:
            authorization-grant-type: password
            client-id:
            client-secret:
            provider: fint-idp
            scope: fint-client

springfox:
  title: 'FINT-Betaling'
  version: '0.0.1-SNAPSHOT'

fint:
#  oauth:
#    enabled: true
#    username: pwfatut
#    password: pwfatut
#    client-id: 6e1cf7b4-b107-42b3-9435-8fda70726c6a
#    client-secret: 6y4FUuP9BfAXeVqguNKT0ofToIwN5RdB1PaUvx_nCMiQbH9NeGq3pp0jQB9zOQ0APOxEbodzJXp-8RVux6318A
#    access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
#    request-url: https://beta.felleskomponent.no/utdanning/elev/person

  client:
    base-url: https://play-with-fint.felleskomponent.no

  betaling:
    client-name: "FINT-Betaling"
    default-org-id: "fake.no"
    default-school-org-id: "970123459"
    date-range: "7, 14, 30"
    invoice-update-cron: "0 30 16 ? * MON-FRI"
    endpoints:
      invoice: "/okonomi/faktura/fakturagrunnlag"
      order-line: "/okonomi/faktura/fakturalinje"
      mva-code: "/okonomi/kodeverk/merverdiavgift"
      employer: "/okonomi/faktura/fakturautsteder"
      skole: "/utdanning/utdanningsprogram/skole"
      basisgruppe: "/utdanning/elev/basisgruppe"
      undervisningsgruppe: "/utdanning/timeplan/undervisningsgruppe"
      kontaktlarergruppe: "/utdanning/elev/kontaktlarergruppe"
      person: "/utdanning/elev/person"
      elevforhold: "/utdanning/elev/elevforhold"
