spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/fintBetaling"

fint:
  betaling-backend:
    client-authorization:
      enable: true
  client:
    base-url: https://play-with-fint.felleskomponent.no

  betaling:
    client-name: "FINT-Betaling"
    org-id: "pwf.no"
    default-org-id: "pwf.no"
    default-school-org-id: "970123458"
    date-range: "7, 14, 30"
    demo: "true"
    demo-user-employeeid: "100006"
    demo-user-org-id: "970123458"
    principal-matching-strategy: "byOrgnummer"
    invoice-update-cron: '0 30 16 ? * MON-FRI'
    endpoints:
      environment: "play-with-fint"
      invoice: "/okonomi/faktura/fakturagrunnlag"
      order-line: "/okonomi/faktura/fakturalinje"
      mva-code: "/okonomi/kodeverk/merverdiavgift"
      employer: "/okonomi/faktura/fakturautsteder"
      skole: "/utdanning/utdanningsprogram/skole"
      basisgruppe: "/utdanning/elev/basisgruppe"
      undervisningsgruppe: "/utdanning/timeplan/undervisningsgruppe"
      kontaktlarergruppe: "/utdanning/elev/kontaktlarergruppe"
      person: "/utdanning/elev/person"
      elevforhold: "/utdanning/elev/elevforhold"

