spring:
  cache:
    caffeine:
      spec: expireAfterWrite=2h
    cache-names: me, schools, basisGroups, teachingGroups, contactTeacherGroups, studentRelations, students, organisations, persons
    type: CAFFEINE
  mvc:
    dispatch-options-request: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token?resourceServer=fint-api
        registration:
          fint:
            authorization-grant-type: password
            provider: fint-idp
            scope: fint-client

management:
  health:
    readinessState:
      enabled: true
  endpoints:
    health:
      probes:
        enabled: true
    web:
      exposure:
        include: info, health, metrics, prometheus

fint:
  betaling:
    date-range: "7, 14, 30"
    invoice-update-rate: "900000"
    invoice-update-cron: '0 30 16 ? * MON-FRI'
    demo-user-employeeid: "100006"
    demo: "false"

