spring:
  mvc:
    dispatch-options-request: true
  data:
    mongodb:
      uri: "mongodb://localhost:27017/fintBetaling"

security:
  basic:
    enabled: false

springfox:
  title: 'FINT-Betaling'
  version: '0.0.1-SNAPSHOT'

fint:
  oauth:
    enabled: false

  betaling:
    client-name: "FINT-Betaling"
    default-org-id: "pwf.no"
    default-school-org-id: "970123459"
    date-range: "7, 14, 30"
    demo: "true"
    demo-user-feide: "nora.lys@osloskole.no"
    principal-matching-strategy: "byOrgnummer"
    invoice-update-cron: '0 30 16 ? * MON-FRI'
    endpoints:
      environment: "play-with-fint"
