spring:
  cache:
    caffeine:
      spec: expireAfterWrite=2h
    cache-names: me, schools, basisGroups, teachingGroups, contactTeacherGroups, studentRelations, students, organisations, persons
    type: CAFFEINE
  mvc:
    dispatch-options-request: true

security:
  basic:
    enabled: false

springfox:
  title: '@title@'
  version: '@version@'

fint:
  betaling:
    date-range: "7, 14, 30"
    invoice-send-rate: "60000"
    invoice-update-rate: "150000"
  oauth:
    enabled: true
    access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
    scope: fint-client
