spring:
  mvc:
    dispatch-options-request: true
  data:
    mongodb:
      uri: "mongodb://localhost:27017/fintBetaling"

security:
  basic:
    enabled: false

springfox:
  title: 'FINT-Betaling'
  version: '0.0.1-SNAPSHOT'

fint:
  oauth:
    enabled: true
    username: "betaling@client.fintlabs.no"
    client-id: "e56a78b9-0f0e-4ff9-846b-46d99fa66d76"
    scope: "fint-client"
    access-token-uri: "https://idp.felleskomponent.no/nidp/oauth/nam/token"
    request-url: https://beta.felleskomponent.no/utdanning/elev/person
  betaling:
    client-name: "FINT-Betaling"
    default-org-id: "fintlabs.no"
    date-range: "7, 14, 30"
    invoice-send-rate: "60000"
    invoice-update-rate: "150000"
    endpoints:
      invoice: "https://beta1.felleskomponent.no/betaling/fakturagrunnlag"
      order-line: "https://beta1.felleskomponent.no/betaling/varelinje"
      mva-code: "https://beta1.felleskomponent.no/betaling/mvakode"
      employer: "https://beta1.felleskomponent.no/betaling/oppdragsgiver"
      student: "https://beta.felleskomponent.no/utdanning/elev/elev"
      skole: "https://beta.felleskomponent.no/utdanning/utdanningsprogram/skole"
      basisgruppe: "https://beta.felleskomponent.no/utdanning/elev/basisgruppe"
      undervisningsgruppe: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe"
      kontaktlarergruppe: "https://beta.felleskomponent.no/utdanning/elev/kontaktlarergruppe"
      person: "https://beta.felleskomponent.no/utdanning/elev/person"
      membership: "https://beta.felleskomponent.no/utdanning/elev/medlemskap"
      student-relation: "https://beta.felleskomponent.no/utdanning/elev/elevforhold"
    endpoints-pwf:
      invoice: "https://beta1.felleskomponent.no/betaling/fakturagrunnlag"
      order-line: "https://beta1.felleskomponent.no/betaling/varelinje"
      mva-code: "https://beta1.felleskomponent.no/betaling/mvakode"
      employer: "https://beta1.felleskomponent.no/betaling/oppdragsgiver"
      student: "https://play-with-fint.felleskomponent.no/utdanning/elev/elev"
      skole: "https://beta.felleskomponent.no/utdanning/utdanningsprogram/skole"
      basisgruppe: "https://play-with-fint.felleskomponent.no/utdanning/elev/basisgruppe"
      undervisningsgruppe: "https://play-with-fint.felleskomponent.no/utdanning/timeplan/undervisningsgruppe"
      kontaktlarergruppe: "https://play-with-fint.felleskomponent.no/utdanning/elev/kontaktlarergruppe"
      person: "https://play-with-fint.felleskomponent.no/utdanning/elev/person"
      membership: "https://play-with-fint.felleskomponent.no/utdanning/elev/medlemskap"
      student-relation: "https://play-with-fint.felleskomponent.no/utdanning/elev/elevforhold"

