apiVersion: apps/v1
kind: Deployment
metadata:
  name: betaling-auth-forward
spec:
  selector:
#    matchLabels:
#      app: betaling-auth-forward
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: betaling-auth-forward
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: ghcr.io/fintlabs/flais-auth-forward-service:sha-692c172
          name: auth-forward
          ports:
            - containerPort: 8080
              protocol: TCP
#          envFrom:
#            - secretRef:
#                name: auth-forward
          env:
            - name: logging.level.no.fintlabs
              value: debug