apiVersion: apps/v1
kind: Deployment
metadata:
  name: betaling-auth-forward
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: ghcr.io/fintlabs/flais-auth-forward-service:sha-65fbbb4
          name: auth-forward
          ports:
            - containerPort: 8080
              protocol: TCP
#          envFrom:
#            - secretRef:
#                name: auth-forward
          env:
            - name: logging.level.no.fintlabs
              value: debug