apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-betaling-backend
  namespace: afk-no
  labels:
    app.kubernetes.io/name: fint-betaling-backend
    app.kubernetes.io/instance: fint-betaling-backend_afk_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: fint-betaling-backend
    app.kubernetes.io/part-of: core
    fintlabs.no/team: core
    fintlabs.no/org-id: afk.no
spec:
  port: 8080
  orgId: afk.no
  image: ghcr.io/fintlabs/fint-betaling-backend:latest
  imagePullPolicy: Always
  env:
    - name: ENV1
      value: test
    - name: ENV2
      value: test
    - name: ENV3
      value: test
  envFrom:
    - secretRef:
        name:

  database:
    database: fint-core
  url:
    hostname: betaling.felleskomponent.no
    basePath: /api/afk-no
  ingress:
    enabled: true
    basePath: /api

  resources:
    limits:
      memory: "5Gi"
      cpu: "2"
    requests:
      memory: "512Mi"
      cpu: "250m"
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }