apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-betaling-backend
  namespace: afk-no
spec:
  port: 8080
  orgId: afk.no
  image: ghcr.io/fintlabs/fint-betaling-backend:latest
  imagePullPolicy: Always
  env:
    - name: fint.betaling.org-id
      value: afk.no
    - name: fint.betaling.default-org-id
      value: afk.no
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx4250M'
    - name: fint.betaling.invoice-update-rate
      value: '3600000'
    - name: fint.betaling.principal-matching-strategy
      value: 'byOrgnummer'
    - name: fint.client.enabled
      value: 'true'
    - name: fint.client.base-url
      value: 'https://api.felleskomponent.no'
    - name: fint.betaling.client-name
      value: 'FINT-Betaling'
    - name: fint.betaling.default-org-id
      value: 'afk.no'
    - name: fint.betaling.default-school-org-id
      value: afk.no
    - name: fint.betaling.date-range
      value: '7, 14, 30'
    - name: fint.betaling.invoice-update-cron
      value: '0 0 0 31 2 ?'
    - name: fint.betaling.endpoints.environment
      value: 'api'
    - name: logging.level.root
      value: 'INFO'
  envFrom:
    - secretRef:
        name: fint-betaling-backend
  database:
    database: fint-core
  url:
    hostname: betaling.felleskomponent.no
    basePath: /afk/api
  ingress:
    enabled: true
    middlewares:
      - fint-betaling-auth-forward-sso
  resources:
    limits:
      memory: "7Gi"
      cpu: "2"
    requests:
      memory: "512Mi"
      cpu: "250m"
  restartPolicy: Always