apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml
namespace: afk-no
commonLabels:
  app.kubernetes.io/name: fint-betaling-backend
  app.kubernetes.io/instance: fint-betaling-backend_afk-no
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-betaling
  fintlabs.no/org-id: afk.no
  fintlabs.no/team: core