apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-betaling-backend
  namespace: fintlabs-no
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-betaling-backend:latest
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx4250M'
    - name: fint.betaling.invoice-update-rate
      value: '60000'
    - name: fint.betaling.principal-matching-strategy
      value: 'byOrgnummer'
    - name: spring.security.oauth2.client.registration.fint.client-id
      value: 'demo'
    - name: fint.oauth.enabled
      value: 'false'
    - name: fint.client.enabled
      value: 'false'
    - name: fint.client.base-url
      value: 'https://play-with-fint.felleskomponent.no'
    - name: fint.betaling.client-name
      value: 'FINT-Betaling'
    - name: fint.betaling.org-id
      value: 'pwf.no'
    - name: fint.betaling.default-org-id
      value: 'pwf.no'
    - name: fint.betaling.default-school-org-id
      value: '970123458'
    - name: fint.betaling.date-range
      value: '7, 14, 30'
    - name: fint.betaling.demo-user-employeeid
      value: '100006'
    - name: fint.betaling.demo
      value: 'true'
    - name: fint.betaling.demo-user-org-id
      value: '970123458'
    - name: fint.betaling.invoice-update-cron
      value: '0 0 0 31 2 ?'
    - name: fint.betaling.endpoints.environment
      value: 'beta'
    - name: logging.level.root
      value: 'INFO'
  database:
    database: fint-core
  url:
    hostname: betaling-demo.felleskomponent.no
    basePath: /demo/api
  ingress:
    enabled: true
    middlewares:
      - fint-betaling-auth-forward-sso
  resources:
    limits:
      memory: "5Gi"
      cpu: "2"
    requests:
      memory: "512Mi"
      cpu: "250m"