apiVersion: apps/v1
kind: Deployment
metadata:
  name: fint-betaling-backend
spec:
#  selector:
#    matchLabels:
#      app: fint-betaling-backend
  template:
    metadata:
#      labels:
#        app: fint-betaling-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: fint-betaling-backend
          image: ghcr.io/fintlabs/fint-betaling-backend:sha-0000000
          resources:
            limits:
              memory: "14Gi"
              cpu: "2"
            requests:
              memory: "6Gi"
              cpu: "250m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fint-environment
          env:
            - {name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx5G'}
            - { name: fint.betaling.principal-matching-strategy, value: 'byOrgnummer' }
            - { name: fint.oauth.enabled, value: 'true' }
            - { name: fint.client.enabled, value: 'true' }
            - { name: fint.client.base-url, value: "https://api.felleskomponent.no" }
            - { name: fint.betaling.client-name, value: "FINT-Betaling" }
            - { name: fint.betaling.date-range, value: "7, 14, 30" }
            - { name: fint.betaling.invoice-update-cron, value: "0 30 16 ? * MON-FRI" }
            - { name: fint.betaling.endpoints.environment, value: "api" }
            - { name: fint.betaling.demo, value: "false" }

