CREATE TABLE claim (
   orgId VARCHAR(255),
   orderNumber BIGINT PRIMARY KEY,
   invoiceNumbers VARCHAR(255),
   createdDate TIMESTAMP,
   lastModifiedDate TIMESTAMP,
   invoiceDate DATE,
   paymentDueDate DATE,
   amountDue BIGINT,
   originalAmountDue BIGINT,
   requestedNumberOfDaysToPaymentDeadline VARCHAR(255),
   customerId VARCHAR(255),
   customerName VARCHAR(255),
   createdByEmployeeNumber VARCHAR(255),
   organisationNumber VARCHAR(255),
   principalCode VARCHAR(255),
   principalUri VARCHAR(255),
   invoiceUri VARCHAR(255),
   status VARCHAR(100),
   statusMessage VARCHAR(255),
   timestamp BIGINT
);
