apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-betaling-backend
  labels:
    app.kubernetes.io/component: backend
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-betaling-backend:latest
  env:
    - name: fint.betaling.principal-matching-strategy
      value: byOrgnummer
    - name: fint.oauth.enabled
      value: 'true'
    - name: fint.client.enabled
      value: 'true'
    - name: fint.client.base-url
      value: https://play-with-fint.felleskomponent.no
    - name: fint.betaling.client-name
      value: FINT-Betaling
    - name: fint.betaling.date-range
      value: 7, 14, 30
    - name: fint.betaling.invoice-update-cron
      value: 0 30 16 ? * MON-FRI
    - name: fint.betaling.endpoints.environment
      value: pwf
    - name: fint.betaling.demo
      value: 'false'
  database:
    database: replace
  onePassword:
    vault: replace
  url:
    hostname: betaling-replace.felleskomponent.no
    basePath: /api
  ingress:
    enabled: true
    basePath: /api
  resources:
    limits:
      memory: 14Gi
      cpu: '2'
    requests:
      memory: 6Gi
      cpu: 250m
