apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs
resources:
  - application.yaml
  - sso.yaml
commonLabels:
  app.kubernetes.io/name: fint-betaling-backend
  app.kubernetes.io/instance: fint-betaling-backend_fintlabs_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: fintlabs.no